### ISSUE TITLE
"TypeError: Cannot read property 'collection' of undefined" when defining a relation

### ISSUE THREAD

**Issue by jgoux** [js-data/js-data-angular#317]
Hello,
I'm trying to define a relation between two factories, but as soon as I define them the application crash with this error : 
```
TypeError: Cannot read property 'collection' of undefined
    at http://localhost:3000/bundle.js:76:17176
    at Object.t [as forEach] (http://localhost:3000/bundle.js:75:24893)
    at e.t (http://localhost:3000/bundle.js:76:16852)
    at e.l.(anonymous function) [as link] (http://localhost:3000/bundle.js:58:2665)
    at http://localhost:3000/bundle.js:76:15863
    at Object.t [as forEach] (http://localhost:3000/bundle.js:75:24893)
    at e.o (http://localhost:3000/bundle.js:76:15658)
    at http://localhost:3000/bundle.js:76:16420
    at Object.t [as forEach] (http://localhost:3000/bundle.js:75:24893)
    at e.s (http://localhost:3000/bundle.js:76:16404)
    at e.l.(anonymous function) [as inject] (http://localhost:3000/bundle.js:58:2665)
    at e.t (http://localhost:3000/bundle.js:76:22920)
    at http://localhost:3000/bundle.js:76:24079
    at u (http://localhost:3000/bundle.js:38:28612)
    at http://localhost:3000/bundle.js:38:28784
    at f.$get.f.$eval (http://localhost:3000/bundle.js:39:4087)
```

Here are my factories : 
```js
.factory("Element", /*@ngInject*/ (DS) => DS.defineResource({
    name: "elements",
    relations: {
      hasMany: {
        "textes-codes": {
          localField: "textesCodes",
          foreignKey: "elementId"
        }
      }
    }
  }))
.factory("TexteCode", /*@ngInject*/ (DS) => DS.defineResource("textes-codes"))
```

The crash happens when I call `Element.findAll()`
I'm using AngularJS 1.4

**Comment by jmdobry** [comment]
Can you provide more info so I can debug?

- good - Your versions of js-data, js-data-angular, etc, relevant console logs/error, code examples w/data that revealed the issue
- better - A [plnkr](http://plnkr.co/), [fiddle](http://jsfiddle.net/), or [bin](http://jsbin.com/?html,output) that demonstrates the issue
- best - A Pull Request that fixes the issue, including test coverage for the issue and the fix

**Comment by jmdobry** [comment]
If the error was thrown inside of js-data then a stack trace would be extremely useful. But, the one you posted just has `bundle.js` and I have no idea what that looks like.

**Comment by jgoux** [comment]
Sorry I don't understand why js-data doesn't have its own sourcemap in my build process.
I disabled uglifyJS to be able to show the function names.
So this is this line : https://github.com/js-data/js-data/blob/a4357e06a7cb9f4c97f0fb5f06a07ad61692eac6/src/datastore/sync_methods/link.js#L35
`_this.s[relationName]` is undefined.
I'm using js-data 1.5.8, js-data-angular 2.2.3 and angularJS 1.4.0-beta.5

Weird fact, angularJS 1.3.14 is also included in my build because js-data-angular downloaded it. :/

Here are the full definition of my two providers : 
```javascript
import ng from "angular"

var moduleName = "sms.services.element"

ng.module(moduleName, [])
  .factory("Element", /*@ngInject*/ (DS) => DS.defineResource({
    name: "elements",
    relations: {
      hasMany: {
        "textes-codes": {
          localField: "textesCodes",
          foreignKey: "elementId"
        }
      }
    }
  }))

export default moduleName
```
```javascript
import ng from "angular"

var moduleName = "sms.services.texte-code"

ng.module(moduleName, [])
  .factory("TexteCode", /*@ngInject*/ (DS) => DS.defineResource("textes-codes"))

export default moduleName
```
And the function call which cause the error : 
```
constructor(Element) {
    this.Element = Element
    this.Element.findAll().then((elements) => { this.elements = elements })
  }
```

Without the relation definition, this code just works fine.
With the relation definition, I can see in the console that my resources are downloaded from the API, but then it crashes just after : 
```
Wed, 18 Mar 2015 19:33:50 GMT - GET http://localhost:8888/elements - 200 658ms Object {data: Array[2], status: 200, headers: function, config: Object, statusText: "OK"}
js-data-debug.js:870elements inject [Object, Object] Options {name: "elements", relations: Object, endpoint: "elements", n: "elements", relationList: Array[1]…} null
js-data-debug.js:870elements get 1BLAT Options {name: "elements", relations: Object, endpoint: "elements", n: "elements", relationList: Array[1]…} null
js-data-debug.js:870elements get 1BLAT Options {name: "elements", relations: Object, endpoint: "elements", n: "elements", relationList: Array[1]…} null
js-data-debug.js:870elements get 1EXF Options {name: "elements", relations: Object, endpoint: "elements", n: "elements", relationList: Array[1]…} null
js-data-debug.js:870elements get 1EXF Options {name: "elements", relations: Object, endpoint: "elements", n: "elements", relationList: Array[1]…} null
js-data-debug.js:870elements linkInverse 1BLAT [] null
js-data-debug.js:870elements get 1BLAT Options {name: "elements", relations: Object, endpoint: "elements", n: "elements", relationList: Array[1]…} null
js-data-debug.js:870elements link 1BLAT ["textes-codes"] null
js-data-debug.js:870elements get 1BLAT Options {name: "elements", relations: Object, endpoint: "elements", n: "elements", relationList: Array[1]…} null
2angular.js:11798TypeError: Cannot read property 'collection' of undefined
    at http://localhost:3000/bundle.js:77454:119
    at Object.forEach (http://localhost:3000/bundle.js:74847:28)
    at DS.link (http://localhost:3000/bundle.js:77441:14)
    at DS.store.(anonymous function) [as link] (http://localhost:3000/bundle.js:46141:35)
    at http://localhost:3000/bundle.js:77359:14
    at Object.forEach (http://localhost:3000/bundle.js:74847:28)
    at DS._link (http://localhost:3000/bundle.js:77355:12)
    at http://localhost:3000/bundle.js:77400:14
    at Object.forEach (http://localhost:3000/bundle.js:74847:28)
    at DS.inject (http://localhost:3000/bundle.js:77399:14)
    at DS.store.(anonymous function) [as inject] (http://localhost:3000/bundle.js:46141:35)
    at DS.processResults (http://localhost:3000/bundle.js:77903:25)
    at http://localhost:3000/bundle.js:77988:61
    at processQueue (http://localhost:3000/bundle.js:32442:28)
    at http://localhost:3000/bundle.js:32458:27
    at Scope.$get.Scope.$eval (http://localhost:3000/bundle.js:33660:28)
```

**Comment by jmdobry** [comment]
You can either force the injection (which has been suggested elsewhere, can't find it right now), or you could register resources with `DS`, and then only inject `DS` everywhere. The difference is you'll have to specify the `resourceName` as the first argument to the methods. Example:

```js
constructor(DS) {
  this.DS = DS
  this.DS.findAll('element').then((elements) => { this.elements = elements })
}
```
