### ISSUE TITLE
Better error reporting when forgetting to inject Angular service before loadRelations

### ISSUE THREAD

**Issue by techniq** [js-data/js-data-angular#343]
While there is a note about inject the angular services before use in the [Angular + JSData quickstart guide](http://www.js-data.io/docs/js-data-angular#quick-start), it seems like some better error reporting could be added to help the user.

I had the following state resolve, and it wasn't clear to me initially that I needed to inject the `Comment` and `FeedbackVote` angular/jsdata services before I attempted to load the relations on `Feedback` (causing the `TypeError: __options.orig is not a function` error to be thrown)

```js
static resolve() {
  return {
    feedback: ($stateParams, Feedback, Comment, FeedbackVote) => Feedback.find($stateParams.id).then(f => f.DSLoadRelations(['comments', 'votes', 'answers'])),
    voteSummary: (feedback) => feedback.voteSummary().then(res => res.data)
  }
}
```

```js
$stateChangeError "feedback.view" - fired when an error occurs during transition. 
  error:  TypeError: __options.orig is not a function
    at http://localhost:8000/jspm_packages/github/js-data/js-data@2.3.0/dist/js-data-debug.js:4734:37
    at Object.forEach (http://localhost:8000/jspm_packages/github/js-data/js-data@2.3.0/dist/js-data-debug.js:2625:28)
    at http://localhost:8000/jspm_packages/github/js-data/js-data@2.3.0/dist/js-data-debug.js:4715:18
    at http://localhost:8000/jspm_packages/github/js-data/js-data@2.3.0/dist/js-data-debug.js:4764:10
    at new QPromise (http://localhost:8000/jspm_packages/github/js-data/js-data-angular@3.1.0/dist/js-data-angular.js:238:10)
    at DS.loadRelations (http://localhost:8000/jspm_packages/github/js-data/js-data@2.3.0/dist/js-data-debug.js:4691:11)
    at Feedbacks.module.exports._utils.default.forEach.def.(anonymous function).(anonymous function) [as DSLoadRelations] (http://localhost:8000/jspm_packages/github/js-data/js-data@2.3.0/dist/js-data-debug.js:3415:31)
    at http://localhost:8000/scripts/pages/feedback/view/controller.js!transpiled:218:28
    at processQueue (http://localhost:8000/jspm_packages/github/angular/bower-angular@1.4.6/angular.js:14681:28)
    at http://localhost:8000/jspm_packages/github/angular/bower-angular@1.4.6/angular.js:14697:27
    at Scope.$get.Scope.$eval (http://localhost:8000/jspm_packages/github/angular/bower-angular@1.4.6/angular.js:15925:28)
    at Scope.$get.Scope.$digest (http://localhost:8000/jspm_packages/github/angular/bower-angular@1.4.6/angular.js:15736:31)
    at Scope.$get.Scope.$apply (http://localhost:8000/jspm_packages/github/angular/bower-angular@1.4.6/angular.js:16033:24)
    at done (http://localhost:8000/jspm_packages/github/angular/bower-angular@1.4.6/angular.js:10548:47)
    at completeRequest (http://localhost:8000/jspm_packages/github/angular/bower-angular@1.4.6/angular.js:10720:7)
    at XMLHttpRequest.requestLoaded (http://localhost:8000/jspm_packages/github/angular/bower-angular@1.4.6/angular.js:10661:9) 
```

**Comment by jmdobry** [comment]
I believe JSData throws an error with a more useful message now. It's something like "<RESOURCE> does not exist!"
